baseURL = 'https://azmisblog.netlify.app'
languageCode = 'en-us'
title = "Azmi's Blog"
theme = 'PaperMod'
[outputs]
home = ["HTML", "RSS", "JSON"]
[pagination]
pagerSize = 5
[params]
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowToc = false
comments = false
[params.homeInfoParams]
Title = "Welcome to my Blog"
Content = "My thoughts, shared with you. One day at a time"
    
[menu]
[[menu.main]]
name = "See all post"
url = "/posts/"
weight = 10